### ISSUE TITLE
`extensions` option is confusing

### ISSUE THREAD

**Issue by caccialdo** [rollup/rollup-plugin-node-resolve#108]
In most rollup plugins, `extensions` is used as a filter option to process or not the file.

In this plugin, `extensions` refers to the extensions that be resolved by the node resolver.

Having it inside `customResolveOptions` would help making this distinction clearer IMO.

**Comment by mecurc** [comment]
Any ideas? I think it can be closed now.

1. I am personally wasn't confused with it
2. We already introduce mainFields that was breaking change and I think introduce yat another breaking change without big reasons is a bad idea.
