### ISSUE TITLE
Entry field from package.json order of preference isn't clear

### ISSUE THREAD

**Issue by caccialdo** [rollup/rollup-plugin-node-resolve#109]
From looking at the options documentation, it is not clear in which order fields inside package.json will be chosen.

IMO organising the options like this would help make the distinction clearer:

```js
{
  main: true,
  jsnext: true,
  browser: true
}
// vs.
{
  entryFields: ['main', 'jsnext:main', 'browser'] // Default to ['main']
}
```

**Comment by shrpne** [comment]
This PR #182 should fit it

**Comment by mecurc** [comment]
I think it can be closed now. Currently we have `mainFields`.
