### ISSUE TITLE
The is-module dep looks pretty dead

### ISSUE THREAD

**Issue by SnarkBoojum** [rollup/rollup-plugin-node-resolve#113]
I notice that rollup-plugin-node-resolve depends on is-module, but that is-module's homepage on npmjs.com leads to a 404 on github.

Wouldn't there be a more viable dep somewhere?

**Comment by revelt** [comment]
I would like to challenge your statement: its homepage-typed-by-url seems to work fine: https://www.npmjs.com/package/is-module, its homepage key in `package.json` is https://github.com/component/is-module and its downloads seem growing and healthy: https://npmcharts.com/compare/is-module

Please confirm you still want to keep this issue open.

**Comment by SnarkBoojum** [comment]
Well, last commit from three years ago isn't very live, but the author answered to my request to tag a release there pretty fast, so indeed I think it's ok to close.
