### ISSUE TITLE
Default to resolving browser dependencies.

### ISSUE THREAD

**Issue by kriskowal** [rollup/rollup-plugin-node-resolve#119]
The defaults for this module use the Node.js-preferred versions of modules by default, which I believe is rarely the intended usage of Rollup. I imagine ignoring the browser redirects would be good for scripts packed for deployment on Amazon Lambda. However, I believe that is a niche compared to folks using Rollup to deploy bundles to the web.

This comes to my attention because folks are using ASAP as a transitive dependency. This provides alternative versions of multiple modules for Node.js and browser deployment.

https://github.com/kriskowal/asap/issues/73

**Comment by TehShrike** [comment]
:+1: 

Rollup works well bundling for the browser, but isn't very good at bundling for node right now.

This module defaulting to `browser: false` feels way out of place, and breaks some builds for a lot of modules.

**Comment by lukastaegert** [comment]
I do not see moment, jest or prettier as niche use-cases. Rollup is currently mainly used for bundling libraries and many of them are isomorphic while some of them are even node-only. Considering that the `browser` field has always been an opt-in field, I would find it somewhat confusing if rollup (i.e. this plugin) would consider it by default.

**Comment by TehShrike** [comment]
eh, in a world where rollup-plugin-commonjs destroys all dynamic imports with no option to prevent it (https://github.com/rollup/rollup-plugin-commonjs/issues/131 + https://github.com/rollup/rollup-plugin-commonjs/blob/058bb8b5b0de0129644b8b442c9a39a3978565cc/src/helpers.js#L6-L8), I don't know if there's a strong argument that Rollup is primarily serving node developers over browser developers right now.

**Comment by kriskowal** [comment]
We should probably pivot this conversation to discovery and documentation. Changing the behavior is probably not tenable, and resolving the question "who is this primarily for" is evidently subjective and controversial. I’d revise my suggestion: Encourage explicitly setting the browser option, regardless of the default, throughout all documentation.

**Comment by lukastaegert** [comment]
Just to make this more confusing, Webpack in fact does default to using the `browser` field: https://webpack.js.org/configuration/resolve/#resolve-aliasfields

Considering that `rollup` is not primarily a web bundler, however, I would go for @kriskowal's suggestion at the moment.

**Comment by TehShrike** [comment]
browserify also respects the `browser` field by default, unless you pass in `--node` or `--no-browser-field`.

I believe most users expectations are being set by the "bundle for the browser, unless you say you're targeting something else" behavior that is the default everywhere else.

Even other Rollup plugins (e.g. rollup-plugin-commonjs) behave this way.

**Comment by lukastaegert** [comment]
Both browserify and webpack were written for the specific purpose of bundling for the browser, though. In contrast to rollup, which is often used for bundling libraries for deployment on npm. I guess there is no right answer.

**Comment by jirutka** [comment]
> Rollup works well bundling for the browser, but isn't very good at bundling for node right now.

Why do you think so? I'm currently started using Rollup to bundle CLI node app and after patching (using [patch-package](https://github.com/ds300/patch-package/)) few outdated modules doing ugly things it works pretty well. I'm impressed how small is the resulting bundle in comparison with size of my node_modules. Sure, it has some limitations (not supporting dynamic requires), so it's not for people who don't know how it works and what are they doing...

**Comment by nsivertsen** [comment]
I would also very much be in favour of Rollup having the same default behaviour here as other major bundlers. Especially now that Rollup has code splitting and is being used increasingly for bundling applications (recent example: [Sapper](https://github.com/sveltejs/sapper) can now [be bundled with Rollup](https://github.com/sveltejs/sapper-template/tree/rollup)! 🎉).

Many "isomorphic" libraries (eg. [superagent](https://github.com/visionmedia/superagent/blob/ff9acc68dae427c853a17526edf71157178eccf8/package.json#L56), [cross-fetch](https://github.com/lquixada/cross-fetch/blob/6019274ecb1a1edfbe8f74d557b1a212c7025e91/package.json#L7)) rely on this behaviour and including them in an app without setting `options.browser = true` results in:

```
Uncaught (in promise) ReferenceError: require is not defined
```

**Comment by mecurc** [comment]
There is no right solution for *ANYTHING* case. Libs are also different.

I think it can be closed now.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
