### ISSUE TITLE
node-resolve doesn't cache lookups

### ISSUE THREAD

**Issue by keithamus** [rollup/rollup-plugin-node-resolve#121]
If node-resolve has found a non-relative module - i.e. one that exists in side `node_modules`, it should cache this lookups - to save time doing subsequent re-lookups, to avoid hitting the disk again.

I am discovering this because one of my modules takes 10ms to resolve using node-resolve (node-resolve needs to read the package.json to determine where the module exists), and this module is used 100 times in the codebase, currently it takes a second of cumulative lookups for this module, but it should be able to hit a cache so only the first hit takes 10ms while subsequent hits should only be 1-2ms at worst. 

Happy to submit a PR if you feel this is correct 😄

**Comment by keithamus** [comment]
Just to give some more context; on a single build of one of the smaller modules, on the codebase I'm on, I instrumented `readFile` just to see how many times a package.json file was read (rather than just hit from a cache) and literally every duplicate file read came from `browser-resolve`, hitting some of my package.json files hundreds of times for one build. Some stats on how many duplicate reads happened:

```js
'<package-root>/package.json': 738,
'<package-root>/<module-1>/package.json': 17,
'<package-root>/<module-2>/package.json': 6,
'<package-root>/<module-3>/package.json': 3,
'<package-root>/<module-4>/package.json': 1,
'<package-root>/<module-5>/package.json': 13,
'<package-root>/<module-6>/package.json': 17
```
(I've had to strip some of the path info because the modules and pathnames are sensitive info)

As you can see during the rollup build; `browser-resolve` read my package.json 738 times! `phase-1` of the rollup build process (which is just resolving the module ids) takes ~2900ms on my machine. `module-1`, `module-2` and `module-6` in the above stats also took the longest to resolve (with `module-6` taking an average of 20ms for this build). So in other words `module-6` was manually resolved 17 times, each time taking ~20ms for a total of 340ms of this particular build. Between `module-1`, `module-6` and `module-5` (all of which, are not only called the most but also take the longest to resolve) we're spending 640ms just re-resolving the same module.

**Comment by lukastaegert** [comment]
Hi @keithamus, without checking this myself (your analysis looks quite thorough 👍), yes, a PR would be very much welcome here!

**Comment by keithamus** [comment]
I haven't forgotten about this! I'll be picking this up next week or the week after.

**Comment by pieterbeulque** [comment]
Hi @keithamus, have you started working on this? I'd be glad to help out.

**Comment by keithamus** [comment]
Not yet. Probably going to have to pick it up in the new year now. Feel free to work on it in the meantime!

**Comment by keithamus** [comment]
I've made the first of a couple of PRs, #126. This cached disk stats and reads from node-resolve. Takes the number of these calls down considerably.

**Comment by mecurc** [comment]
Currently, plugin caches files (https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L15, https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L26).

Can it be closed now? Or we waiting for some enhancements?

**Comment by keithamus** [comment]
Oh yeah, we can close this now. Thanks @mecurc!
