### ISSUE TITLE
Inconsistent module name case results in duplicate imports

### ISSUE THREAD

**Issue by jlmakes** [rollup/rollup-plugin-node-resolve#124]
I have a NPM package `tealight` (all lowercase) that contains a few utilities. I noticed I mistakenly used a capital "T" when importing the package in one of my files, and instead of failing (because capital letters are invalid in package names), it simply imported the relevant bits of the library a second time.

```js
// module-a.js
import { deepAssign, each } from 'tealight'
```

```js
// module-b.js
import { each } from 'Tealight' // Oops, capital "T" that's not right!
```

So I ended up with identical functions `each` and `each$1`.

**Comment by mecurc** [comment]
With latest version there are 0 identical functions. Can be closed now.

Repro here: https://github.com/rollup/rollup-plugin-node-resolve/issues/124
