### ISSUE TITLE
Bundle only parts of an external dependency

### ISSUE THREAD

**Issue by chapati23** [rollup/rollup-plugin-node-resolve#125]
Hi,
I'm trying to import and bundle only _a part_ of an external lib with my library. Is this possible with the current implementation?

```js
// my lib
import someFunction from 'main-package/some-function'

export const lalala = someFunction()
```

```js
// the relevant part of my rollup.config.js
export default {
    // ...
    customResolveOptions: {
      moduleDirectory: ['node_modules', 'src']
    }
    ||
```

As far as I can see, this currently leads to _all_ of `main-package` to be included in my bundle.
Is it possible to bundle _just_ `main-package/some-function`?

**Comment by mecurc** [comment]
Yes, you can. Try:
```JavaScript
import { somefunction } from 'some-lib';
```

Can be closed now.
