### ISSUE TITLE
3.0.1 and 3.0.2 have a regression on file size

### ISSUE THREAD

**Issue by Haroenv** [rollup/rollup-plugin-node-resolve#130]
see https://github.com/algolia/react-instantsearch/pull/831#issuecomment-356993628 and [size diff](https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A8192%2C%22path%22%3A%22packages%2Freact-instantsearch%2Fdist%2Fumd%2FCore.min.js%22%2C%22size%22%3A7494%2C%22master%22%3A7494%7D%2C%7B%22maxSize%22%3A38912%2C%22path%22%3A%22packages%2Freact-instantsearch%2Fdist%2Fumd%2FConnectors.min.js%22%2C%22size%22%3A44771%2C%22master%22%3A38225%7D%2C%7B%22maxSize%22%3A63488%2C%22path%22%3A%22packages%2Freact-instantsearch%2Fdist%2Fumd%2FDom.min.js%22%2C%22size%22%3A71426%2C%22master%22%3A62132%7D%5D%2C%22repo%22%3A%22algolia%2Freact-instantsearch%22%2C%22branch%22%3A%22renovate%2Frollup-plugin-node-resolve-3.x%22%2C%22commit_message%22%3A%22Merge%20cdedf7ac8528ef7fcda0549f2993b154d0f793c9%20into%20ef6e454b7b83cf2be793c69f5ecacc56558a509d%22%2C%22sha%22%3A%22cdedf7ac8528ef7fcda0549f2993b154d0f793c9%22%7D)

Not sure if this is enough information? 

cc @keithamus and @Rich-Harris

**Comment by keithamus** [comment]
Fascinating. FWIW I ran this through our builds and the patch generated identical checksums with/without the patch, so I'm surprised to see this. Does your build generate sourcemaps? It might be useful to diff the sourcemap as it'll enumerate all of the files in the output.

**Comment by Haroenv** [comment]
I can see that `buffer` gets the node package instead of the browser one. `algoliasearch` gets the parse version, see my repro here: https://github.com/Haroenv/rollup-node-diff

**Comment by samouss** [comment]
In the `3.0.0` Rollup is able to resolve the `algoliasearch/lite` but not with the `3.0.2`.

https://github.com/algolia/algoliasearch-client-javascript/blob/58a4b2dbe6258769a869e2668d0d66367359504c/package.json#L5-L10

**Comment by keithamus** [comment]
Ah, so for `algoliasearch` the `main` key says `index.js` while the browser field has `./index.js`. I will look into how to resolve that.

`buffer` could be because `node-resolve` sees this as a core module, and skips resolution logic. I'll look into this one too.
