### ISSUE TITLE
Add `externalBuiltins` option or make them external by default.

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup-plugin-node-resolve#146]
This is a proposal in response to https://twitter.com/SavePointSam/status/975146310855622656

At the moment if someone wants to bundle everything but keep builtins as external dependencies, they have to do something like this:

```javascript
import resolve from 'rollup-plugin-node-resolve';

export default ({
  input: 'src/index.js',
  plugins: [resolve()],
  external: ['path', 'fs', ...],
  output: {
    file: 'build/server.js',
    format: 'cjs'
  }
})
```

i.e. they have to list all builtins manually in their externals list (and adapt this manually in the future). My feeling is that `rollup-plugin-node-resolve` already has the necessary dependencies to trivially implement an option `externalBuiltins` to do that for the user, i.e. the example could become

```javascript
import resolve from 'rollup-plugin-node-resolve';

export default ({
  input: 'src/index.js',
  plugins: [resolve({externalBuiltins: true})],
  output: {
    file: 'build/server.js',
    format: 'cjs'
  }
})
```

Would like some feedback before preparing a PR (maybe this is already possible in some way?)
cc @keithamus, @guybedford

**Comment by keithamus** [comment]
Hm, please correct me if I'm wrong - maybe I'm not understanding the problem - but `rollup-plugin-node-resolve` doesn't actually resolve builtins. See https://github.com/rollup/rollup-plugin-node-resolve/blob/7846a19da76e84f81f349162e6cf281550f6a67d/src/index.js#L172-L173

In fact with a small repo using your first config, I get the following output:

```bash
$ rollup -c rollup.config.js
src/index.js → build/server.js...
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
fs (imported by index.js)
created build.js in 15ms

$ cat build/server.js
'use strict';
var fs = require('fs');
console.log(fs.readFile('x'));
```

**Comment by lukastaegert** [comment]
Yes, but it gives you a warning for each builtin that user's have to silence by filling the `external` field. My suggestion is to add a switch to silence these warnings all at once. So the implementation could just become

```javascript
if ( ~builtins.indexOf( resolved ) ) { 
 	fulfil( externalBuiltins ? false : null ); 
```

making use of the fact the `false` is interpreted as "mark as external and do not further try to resolve this via other plugins". But it is also important to not make things more confusing.

**Comment by keithamus** [comment]
Adding an option just to silence a warning seems - to me - that it does not really meet the complexity-benefit-tradeoff; as you've demonstrated it certainly would be a simple change to implement but another option to document and more complexity inherited by people consuming the plugin. We could instead look to document how to acheive this without changes to this code:

```js
import resolve from 'rollup-plugin-node-resolve';
import builtins from 'builtin-modules'
export default ({
  input: 'src/index.js',
  plugins: [resolve()],
  externals: builtins,
  output: {
    file: 'build/server.js',
    format: 'cjs'
  }
})
```

**Comment by lukastaegert** [comment]
Yes, the alternative would be to add this example to the documentation.

**Comment by guybedford** [comment]
This is definitely useful, great suggestion!

Could also be worth considering if this should be a more generic `node: true` build option as well.

**Comment by mmomtchev** [comment]
Anything new on this subject? How do you do it at the moment, you add all the built-ins to external?

**Comment by franhaselden** [comment]
Also interested in this

**Comment by mecurc** [comment]
Any updates?

**Comment by keithamus** [comment]
@mmomtchev @franhaselden @mecurc please take a look at https://github.com/rollup/rollup-plugin-node-resolve/issues/146#issuecomment-374163293; providing `builtins` to the `externals` option sufficiently silences these warnings.
