### ISSUE TITLE
doesn't work with  `rollup-plugin-alias`

### ISSUE THREAD

**Issue by foisonocean** [rollup/rollup-plugin-node-resolve#152]
I'm using `preact` and `preact-compat`.
I don't use `react` directly in my code, but some of my dependencies are based on `react` rather than `preact`, so I need to map `react` and `react-dom` to `preact-compat`.
here is my rollup config:

```js
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import replace from 'rollup-plugin-replace';
import alias from 'rollup-plugin-alias';

const config = {
  plugins: [
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
    }),
    commonjs({
      include: 'node_modules/**',
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
    }),
    alias({
      react: 'preact-compat',
      'react-dom': 'preact-compat',
    }),
  ]
};
```

And I got this error when I run rollup:

```
[!] Error: Could not load preact-compat (imported by ....../node_modules/react-slick/lib/slider.js): ENOENT: no such file or directory, open 'preact-compat'
```

**Comment by newlifeyh** [comment]
I think you can have a full path alias, like:
alias({
   react: path.resolve(__dirname, 'node_modules/preact-compat')
})

**Comment by allex** [comment]
Actually, rollup stoped resolve lifecycle if the `importee` resolved by any plugin.
i've add `alias` options for [builtin support alias][https://github.com/allex/rollup-plugin-node-resolve].

```
import nodeResolve from '@allex/rollup-plugin-node-resolve'
...
 nodeResolve({
    react: 'preact-compat',
    'react-dom': 'preact-compat',
})
...
```

**Comment by lukastaegert** [comment]
Just a note if anyone feels up to this: I should not be too difficult to enhance rollup-plugin-alias to further resolve aliases via other plugins. Rollup provides `this.resolveId` to plugins to do just that. It just takes someone to take the initiative here.

**Comment by rmacklin** [comment]
@lukastaegert I'm not experienced with rollup plugins but would be interested in helping solve this. Can you share an example of an existing plugin that uses another plugin to further resolve import identifiers? Or if that doesn't exist, is there a general example to follow of how a plugin should call another plugin? That would be helpful in getting started on this.

**Comment by lukastaegert** [comment]
I am on a trip and only have a phone so I can only give you some pointers for now. Not sure if there are plugins in the wild that use the relatively new resolveId helper on the plugin context. It is documented here: https://rollupjs.org/guide/en#plugin-context

Basically what should happen is that you pass the value the alias stands for to this.resolveId as importee in the plugin. The open question is what you should use as importer. I assume the rollup-plugin-alias is resolving either relative to the current working directory, the rollup config file or the importing file so you could pass the name of a non-existing dummy file at that location. This could also make some custom logic in rollup-plugin-alias obsolete. Here is a very simplified version what this could look like:

```ja
export default () => ({
  resolveId(importee, importer) {
    if (importee === someAlias) {
      return this.resolveId(whatTheAliasStandsFor, process.cwd());
    }
    return null;
  }
});
```

**Comment by rmacklin** [comment]
Thanks for the pointers! I was having trouble with it because there's [logic in `rollup-plugin-alias`](https://github.com/rollup/rollup-plugin-alias/blob/b32d8f5d895fe7524f237b7f40cceabecf33dfeb/src/index.js#L21) that does not work well with the aliases I am using:
```js
{
  mitt: 'mitt/src',
  'preact-portal': 'preact-portal/src/preact-portal',
  'preact-router': 'preact-router/src'
}
```
Basically, it would turn an import like
`import Router from 'preact-router'`
into
`import Router from 'preact-router/src'`
(correctly), but then it would recurse and turn that into
`import Router from 'preact-router/src/src'`
and then
`import Router from 'preact-router/src/src/src'`
and so on.

I was adding code to fix that, but as I got deeper into the code it seemed like `rollup-plugin-alias` was really meant for aliasing relative path imports, which does not match my use case. For me, this simple custom plugin:
```js
const rollupAlias = aliases => ({
  resolveId(importee) {
    const alias = aliases[importee];

    return alias ? require.resolve(alias) : null;
  }
});
```
is sufficient, so I'm going with that instead of `rollup-plugin-alias` for now.

**Comment by mecurc** [comment]
Can be closed now.

**Comment by vpalos** [comment]
The `alias` plugin no longer resolves module names, but you can easily use `require.resolve` to achieve this:
```js
alias({
      react: require.resolve("preact/compat"),
      "react-dom": require.resolve("preact/compat")
    })
```

**Comment by viT-1** [comment]
@vpalos Please show us full rollup configuration example (with rollup-plugin-node-resolve and may be rollup-plugin-typescript2).

**Comment by rwwagner90** [comment]
Would love an example here as well. I cannot figure out how to use preact-compat with rollup at all.
