### ISSUE TITLE
It looks like to interfere with tree-shaking

### ISSUE THREAD

**Issue by molszanski** [rollup/rollup-plugin-node-resolve#153]
Hi guys, 

it looks like this plugin has some unintended side effect. 

```bash
molszanski  staff   139K Apr 12 14:38 index.with_node_resolve.js
molszanski  staff   106B Apr 12 14:38 index.without_node_resolve.js
```
Here is an [example repo](https://github.com/molszanski/rolllup-node-resolve-treeshake-bug).

Adding node-resolve to the setup below will interfere with tree-shaking and will increase the bundle-size. 

```js
// index.js
import { fun1 } from "./module";
fun1();

// module.js
import { stuff } from "some_module";
export function fun1() {
  console.log("123");
}
```

**Comment by lukastaegert** [comment]
An easy way to prevent this is to specifically mark 'mobx'  as external in your rollup configuration. If you also add 'treeshake.pureExternalModules: true', the import will be entirely removed.

**Comment by molszanski** [comment]
My initial surprise was when 2 of the configs below did produce different results. 
Even adding pure treeshake didn't help.

```js

// Configu result - 139K
const js = {
  input: "src/index.js",
  output: [
    {
      file: "dist/index.with_node_resolve.js",
      format: "iife",
      name: "test"
    }
  ],
  treeshake: { pureExternalModules: true },
  plugins: [nodeResolve()]
};

// Config result - 106B
const js_withouth = {
  input: "src/index.js",
  output: [
    {
      file: "dist/index.without_node_resolve.js",
      format: "iife",
      name: "test"
    }
  ]
};
```

**Comment by molszanski** [comment]
But adding external "marker" did the trick

```js
// Config result - 106B
const happyConfig ={
  ...
  plugins: [nodeResolve()]
  external: ["mobx"];
};
```

**Comment by molszanski** [comment]
Maybe it would be a good idea to drop a line or two into the docs about it for the next adventurer :)

**Comment by lukastaegert** [comment]
The behaviour is described here: https://rollupjs.org/guide/en#peer-dependencies

If you think this should be extended, featured more prominently, or linked to from specific other places of the documentation we are always open to suggestions.

**Comment by lukastaegert** [comment]
You can always directly contribute to the documentation here: https://github.com/rollup/rollupjs.org
