### ISSUE TITLE
Unable to resolve require of directories

### ISSUE THREAD

**Issue by vergara** [rollup/rollup-plugin-node-resolve#154]
How to reproduce:
require('./api');
where './api' is a directory. Expected behavior is to import files under the './api' folder.

This can be reproduced with the jsforce library:
npm i jsforce

import jsforce from 'jsforce';

Failure:
ENOENT: no such file or directory, open

**Comment by mecurc** [comment]
its not expected behavior. Node works in another way.
You should have `index.js` file inside folder or you shoud directly import files.

Can be closed now.
