### ISSUE TITLE
Strange code after upgrading up from v3.1.0

### ISSUE THREAD

**Issue by uNmAnNeR** [rollup/rollup-plugin-node-resolve#155]
Hello!

I use node-resolve-plugin in my project [imaskjs](https://github.com/uNmAnNeR/imaskjs) for importing some core-js polyfills.

After upgrading plugin up from v3.1.0 some strange code with `Object.freeze...` appears:
[compiled with v3.1.0](https://gist.github.com/uNmAnNeR/192bcff423cb0563597dbd5b5fb0e768/7c770af2b29e8c9eab3eb3dc6826cc067d825e91)
[compiled with v3.3.0](https://gist.github.com/uNmAnNeR/192bcff423cb0563597dbd5b5fb0e768/5172f8635f760f3306e4331fc6cef0e4341af0f2)
[diff](https://www.diffnow.com/?report=w248e)
which increases compiled size.

Is it really needed?
No mistake here?

**Comment by lukastaegert** [comment]
Hi @uNmAnNeR, thanks for the issue. So you are saying the *only* dependency that changed is `rollup-plugin-node-resolve`, i.e. both builds use the exact same version of `rollup`? It would be very helpful if you could confirm this as this seems very related to the observations in rollup/rollup#2130

**Comment by uNmAnNeR** [comment]
Yes, the only one.
So, previous builds were:
[build rollup@0.58.1, node-resolve@3.1.0](https://gist.github.com/uNmAnNeR/192bcff423cb0563597dbd5b5fb0e768/7c770af2b29e8c9eab3eb3dc6826cc067d825e91)
[build rollup@0.58.1, node-resolve@3.3.0](https://gist.github.com/uNmAnNeR/192bcff423cb0563597dbd5b5fb0e768/5172f8635f760f3306e4331fc6cef0e4341af0f2)

But lets do some more tests.
Rollback to:
[build rollup@0.54.1, node-resolve@3.0.2](https://gist.github.com/uNmAnNeR/192bcff423cb0563597dbd5b5fb0e768/ec5019b8d308374c99edb6bf352ecc720a0a216f)
Update rollup:
[build rollup@0.58.1, node-resolve@3.0.2](https://gist.github.com/uNmAnNeR/192bcff423cb0563597dbd5b5fb0e768/0813d812d3effc4feeae63eb6083625423bd4281)
[diff rollup 0.54.1->0.58.1](https://www.diffnow.com/?report=l4iqt)
Than update node-resolve:
[build rollup@0.58.1, node-resolve@3.3.0](https://gist.github.com/uNmAnNeR/192bcff423cb0563597dbd5b5fb0e768/594937db488269ace0f0a2911cfd209553d0ff76)
[diff node-resolve 3.0.2 -> 3.3.0](https://www.diffnow.com/?report=y7hwr)

So in _BOTH_ updates some new code with `/*#__PURE__*/Object.freeze` appeared!

**Comment by uNmAnNeR** [comment]
Fixed in [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs/pull/313)
