### ISSUE TITLE
error "Could not resolve entry (<module>)" when using manualChunks

### ISSUE THREAD

**Issue by reinaldoarrosi** [rollup/rollup-plugin-node-resolve#164]
When using the following rollup.config.js

```javascript
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';

export default [
    {
        experimentalCodeSplitting: true,
        input: [
            './index.jsx', 
            './page1.jsx'
        ],
        output: {
            dir: './dist',
            format: 'system'
        },
        manualChunks: {
            'vendor': ['react']
        },
        plugins: [
            resolve({ extensions: ['.jsx', '.js'] }),
            commonjs(),
            babel({ exclude: 'node_modules/**' })
        ]
    }
];
````
Rollup gives the error "Could not resolve entry (react)". If I remove the `manualChunks` option everything works fine.

I'm opening this issue because of the discussion in https://github.com/rollup/rollup/issues/2248

**Comment by guybedford** [comment]
As discussed there, the issue seems to be here that top-level imports are not necessarily supported through this plugin - `input: 'node-package-name'`.

**Comment by samjacoby** [comment]
As best as I can figure, this is the recommended way to make a vendor bundle with, say, `react` — using Rollups chunk support (https://github.com/rollup/rollup/pull/2084). 

Wonder if anyone has any thoughts/guidance on fixing this issue (happy to take a look, but I'll need some guidance, as I'm new to the rollup world). Or is there another supported pathway anyone's aware of? This seems like a fairly common use case.

**Comment by guybedford** [comment]
@samjacoby I believe the fix would be to ensure that this plugin can resolve properly handle the resolution scenario - `resolveId('package-name', undefined)`. If you're willing to work on this that would be great - I'd be happy to review.

**Comment by isao** [comment]
Also, with only the logging statement, the output is:
```
./src/app.tsx → dist/bundle.js...
importee ./src/app.tsx, importer: undefined
importee preact, importer: undefined
[!] Error: Could not resolve entry (preact)
```

**Comment by LeeeeeeM** [comment]
not friendly to use

**Comment by seanpoulter** [comment]
I was having a look at this earlier today. Do we need any more information from rollup to know when we're looking at these entries? Is that the only time the `importer` is `undefined` [here](https://github.com/rollup/rollup-plugin-node-resolve/blob/b2ecf57de88849d7dbf41192f68dd98ea8bd387d/src/index.js#L87)?

I tried something like @isao suggested but my "bs-platform" still wasn't resolved. 😭
