### ISSUE TITLE
Master branch not published to npm

### ISSUE THREAD

**Issue by antstanley** [rollup/rollup-plugin-node-resolve#169]
Cloned the master branch of the repo and ran npm install it generated two files in /dist, namely rollup-plugin-node-resolve.es.js and rollup-plugin-node-resolve.cjs.js

When I run npm install --save-dev rollup-plugin-node-resolve and check node_modules/rollup-plugin-node-resolve/dist and compare the files they are different, with the installed files not having any of the .mjs updates. Double checking package.json it shows the latest version is installed "rollup-plugin-node-resolve": "^3.3.0"

Am running npm 6.1.0 & node 10.6.0

---
Discovered whilst trying to diagnose the issue in [#168](https://github.com/rollup/rollup-plugin-node-resolve/issues/168) around .mjs support. Found that the changes had actually been made, but just weren't published to npm for some reason.

**Comment by TrySound** [comment]
Yes, it wasn't published yet.

**Comment by TrySound** [comment]
Does `extensions` option solve your problem for now?

**Comment by antstanley** [comment]
Can confirm the adding `extensions: [ '.mjs','.js', '.json', '.node' ]` in the options I pass to `rollup-plugin-node-resolve` does resolve the issue for now

**Comment by mecurc** [comment]
Seems like it resolved in the current version. Can be closed now.
