### ISSUE TITLE
rollup-plugin-node-resolve not resolving dependency

### ISSUE THREAD

**Issue by brucou** [rollup/rollup-plugin-node-resolve#172]
This is going to be a pretty easy question, but after reading and rereading documentation, and a thousand different trials, I still cannot get my library to resolve my dependencies. 

Directory hierarchy is :

    root
     |-- package.json
     |-- rollup.config.js
     |-- node_modules
         |-- fast-json-patch
         |-- fp-rosetree
         |-- deep-equal

Rollup config file is :

    import resolve from 'rollup-plugin-node-resolve';
    import commonjs from 'rollup-plugin-commonjs';
    import { terser } from "rollup-plugin-terser";
    
    export default {
      input: 'src/index.js',
      output: {
        file: 'dist/transducer.umd.js',
        format: 'umd',
        name: 'StateTranducer',
      },
      plugins: [
        resolve({
          module: true, // Default: true
          jsnext: false,  // Default: false
          main: true,  // Default: true
          browser: true,  // Default: false
          extensions: [ '.mjs', '.js', '.jsx', '.json' ], 
          preferBuiltins: false,  // Default: true
          // Lock the module search in this path (like a chroot). Module defined
          // outside this path will be marked as external
          // jail: '/my/jail/path', // Default: '/'
    
          // Set to an array of strings and/or regexps to lock the module search
          // to modules that match at least one entry. Modules not matching any
          // entry will be marked as external
          only: [
            /^fp-rosetree$/,
          ], // Default: null
          modulesOnly: false, // Default: false
        }),
        commonjs({
          include: ['node_modules/**', "node_modules/deep-equal/**"],
        }),
        terser()
      ]
    };

then my code has 

    import { applyPatch } from "fast-json-patch/"

The [`fast-json-patch`](https://github.com/Starcounter-Jack/JSON-Patch) library in its code features a `var _equals = require('deep-equal');`. In terminal, the error message I get is :

    (!) Missing global variable name
    Use output.globals to specify browser global variable names corresponding to external modules
    deep-equal (guessing 'deepEqual')

As the module [`deep-equal`](https://github.com/substack/node-deep-equal) can be found in `node_modules` directory, I expect rollup to be able to resolve it.  I even ran `npm install` in `node_modules/fast-json-patch` to install `deep-equal` in the `node_modules/fast-json-patch/node_modules` but that still failed to produce any result.

Note that `fp-rosetree` is correctly resolved, and fast-json-patch is a commonjs module, as you can guess from the rollup config.

What can I be missing?

**Comment by Rob-pw** [comment]
@guybedford could you shed a little light into how to resolve node_modules relative to the root project directory?

**Comment by guybedford** [comment]
The code path - https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L87 needs to be removed. It may be as simple as that one line, setting the `importer` to the cwd. It will need a test.

**Comment by mecurc** [comment]
I tried to reproduce it and got no errors. Can be closed now.

**Comment by bionicles** [comment]
still having this issue with imported node_modules in default svelte/template app ... uuidv4 needs rng which needs crypto, and it doesn't compile. ugh
