### ISSUE TITLE
Wiki page linked in readme does not exist

### ISSUE THREAD

**Issue by domoritz** [rollup/rollup-plugin-node-resolve#176]
The readme links to https://github.com/rollup/rollup/wiki/jsnext:main but the page does not exist.

**Comment by lukastaegert** [comment]
`jsnext:main` has by general consensus been superseded by the `module` field. This one still has 
a wiki link: https://github.com/rollup/rollup/wiki/pkg.module

Would you be willing to make a PR to remove the `jsnext:main` field + link and add the wiki link to the module field?

**Comment by domoritz** [comment]
I have a lot of things to catch up on right now and would appreciate if someone else could take care of this. Thanks!

**Comment by mecurc** [comment]
I don’t see links to it in the current README, can it be closed?

**Comment by domoritz** [comment]
Yep, looks like it's been fixed. Thanks!
