### ISSUE TITLE
Rollup package axios, can not be used

### ISSUE THREAD

**Issue by BlackHole1** [rollup/rollup-plugin-node-resolve#181]
Axios is used in the project, then packaged using rollup.

On the browser side, it is normal. But the error is reported on the nodejs side.

error info:

![](https://i.stack.imgur.com/FUuPe.png)

I created a demo that will be available for you to view: https://github.com/BlackHole1/rollup-axios-error-demo

When I comment out the `resolve`, nodejs will run normally. But the browser will not work.

The code for axios source code to distinguish the running environment is:

![](https://camo.githubusercontent.com/828492b53f04d5aa065fd529b130ca02f310c278/687474703a2f2f6f6e377230747167752e626b742e636c6f7564646e2e636f6d2f466d694355474b71712d476c78613058477474673379645a627638692e706e67)

But after packaging, it becomes:

![](https://camo.githubusercontent.com/36b33f1395df9a80a245e2a2b02a36bef695bd3c/687474703a2f2f6f6e377230747167752e626b742e636c6f7564646e2e636f6d2f466e65377143527753454b71455837517942744f4879465f765336332e706e67)

Caused the XMLHttpRequest to be instantiated on the nodejs side

**Comment by mecurc** [comment]
https://github.com/axios/axios/issues/1259

**Comment by mecurc** [comment]
Axios so strange and old package. All problems because axios has terribly old codebase.

I successfully run axios with node. See repo here: https://github.com/mecurc/181-rollup-issue

Can be closed now! :)
