### ISSUE TITLE
Linux resolver

### ISSUE THREAD

**Issue by greg-benner-klick-sensei** [rollup/rollup-plugin-node-resolve#194]
I'm wondering if there is any possibility of Linux being a factor in incorrect path resolution.
We have a config for rollup that works on macOS and Windows. When I tested on Ubuntu on Windows and also a cloud version of linux (Azure DevOps) I get
```[19:18:32] Error: Could not resolve '../constants/MimeTypes.js' from src/main/util/createVirtualStylesheet.js
2019-01-02T19:18:33.9240494Z > gulp build
2019-01-02T19:18:33.9241158Z     at error (/home/vsts/work/1/s/node_modules/rollup/dist/rollup.js:224:15)
2019-01-02T19:18:33.9241201Z 
2019-01-02T19:18:33.9241751Z     at /home/vsts/work/1/s/node_modules/rollup/dist/rollup.js:19454:25
```

Everything I've read points to a couple plugins, and we already are using them. Since it works on macOS (and windows command line) I'm wondering if it could be linux somehow?

```const rollup_commonjs = require('rollup-plugin-commonjs')
const rollup_nodeResolve = require('rollup-plugin-node-resolve')

module.exports = {
	input: '_index.js',
	plugins: [rollup_commonjs(), rollup_nodeResolve()],
	external: ['chroma-js'],
	output: {
		file: 'main.js',
		globals: {
			'chroma-js': 'chroma',
		},
	},
}```

**Comment by AmySteam** [comment]
Oh I ran into this problem before! I had to put resolve () before commonjs().
You can read more about it here: [README](https://github.com/rollup/rollup-plugin-node-resolve#using-with-rollup-plugin-commonjs)
Best wishes! Amy

**Comment by mecurc** [comment]
Seems like the issue was resolved, Can we close it?
