### ISSUE TITLE
(!) Unresolved dependencies https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency

### ISSUE THREAD

**Issue by Dylanwooo** [rollup/rollup-plugin-node-resolve#199]
I try to import a third party package, but I got this warning:
![2019-02-27 4 29 48](https://user-images.githubusercontent.com/19762038/53476268-edce0a80-3aac-11e9-97b2-987977813d9b.png)

I have already used the `resolve` plugin as the [docs](https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency) suggests but still got this warning

here is my config and is quite simple:
<img width="252" alt="2019-02-27 4 35 10" src="https://user-images.githubusercontent.com/19762038/53476584-b1e77500-3aad-11e9-83d4-02fbe87ffeb0.png">

and this is the file where I import the third party package:
<img width="392" alt="2019-02-27 4 36 22" src="https://user-images.githubusercontent.com/19762038/53476701-f410b680-3aad-11e9-9ea7-7e8da6d0cdb7.png">

**Comment by ultrafez** [comment]
The README states that most packages we import are CommonJS modules, and so the rollup-plugin-commonjs plugin is required ([see docs](https://github.com/rollup/rollup-plugin-node-resolve#using-with-rollup-plugin-commonjs)). Does this help?

**Comment by mecurc** [comment]
No updates here and can't reproduce it because can't install `@jmfe/jm-common`. I think it can be closed.

**Comment by cxytomo** [comment]
I encounter the same issue. After I bringing in commonjs and resolve plugins, the problem still exists.

// rollup.config.js
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
  input: 'src/main.js',
  output: {
    file: 'bundle.js',
    format: 'cjs'
  },
  name: 'fp',
  plugins: [
    resolve(),
    commonjs()
  ]
};

I import Fingerprint2  as a third party package

**Comment by cxytomo** [comment]
Problem solved. Make sure the name of wanted package is right.
