### ISSUE TITLE
Rename this plugin

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-node-resolve#20]
`npm` is a misnomer. All this plugin is really doing is wrapping `node-resolve` and `browser-resolve`. I think it would probably make sense to rename this package to rollup-plugin-node-resolve. Thoughts?

**Comment by TrySound** [comment]
I'd prefer only one word. Maybe `node`

**Comment by Rich-Harris** [comment]
We were thinking about using `node` for an all-encompassing plugin that combines the resolution with the CommonJS conversion, built-ins, etc. Is `noderesolve` better? We do already have plugins like coffee-script and multi-entry and browserify-transform

**Comment by Victorystick** [comment]
I'm for `node-resolve`. Its purpose is clear and it is explicit about what library it builds upon.

**Comment by eventualbuddha** [comment]
:+1: `node-resolve`

**Comment by callumlocke** [comment]
:+1: node-resolve

**Comment by Rich-Harris** [comment]
Done
