### ISSUE TITLE
Customize path to node_modules

### ISSUE THREAD

**Issue by runspired** [rollup/rollup-plugin-node-resolve#21]
It's possible rollup is being used by an app with different node modules directory, it's also possible it's being used from within another build step which necessitates a custom directory.

**Comment by TrySound** [comment]
@runspired You can see here how resolve algorithms works
https://nodejs.org/docs/v0.4.8/api/all.html#all_Together...

**Comment by TrySound** [comment]
@runspired Can you describe your case?

**Comment by runspired** [comment]
@TrySound at the point this plugin is used, I've already funneled needed modules from external dependencies into a tmp directory alongside the main project.  I was able to resolve this using rollup-plugin-includepaths instead.

**Comment by differui** [comment]
I got same situation.It looks like `node-resolve` dosen't respect `NODE_PATH`.
