### ISSUE TITLE
[comunity] Issues templates and tags

### ISSUE THREAD

**Issue by mecurc** [rollup/rollup-plugin-node-resolve#214]
We really need this!

Last three days I work with issues here. it's painfully sometimes. I think if we make issues templates our life will be better.

But I am bad with English and I cannot do it. Anyone can send a PR?

P.S. Tag it with `good first issue`, `help wanted` please :)

**Comment by TrySound** [comment]
You are good enough. Try to provide something simple. Package, node versions and os, current behaviour and expected behaviour. Bad english may be fixed by somebody else.

**Comment by TrySound** [comment]
And big thanks for your work

**Comment by lukastaegert** [comment]
Big thanks from my side as well. You might copy/adjust Rollup's own issue templates from here: https://github.com/rollup/rollup/tree/master/.github

Reusing those would probably also improve coherence of the ecosystem. There are also targeted issue templates in https://github.com/rollup/rollup/tree/master/.github/ISSUE_TEMPLATE

**Comment by lukastaegert** [comment]
Closed via #217
