### ISSUE TITLE
How to handle optionalDependencies

### ISSUE THREAD

**Issue by leeyeh** [rollup/rollup-plugin-node-resolve#24]
Some packages with optionalDependencies will require them within try-catch: 

``` javascript
var memcpy = null; try { memcpy = require("memcpy"); } catch (e) {}
if (memcpy) //...
```

Rolling them up will throw `Cannot find module 'memcpy'`.

How to ignore these packages entirely? The 'skip' option only treat them as external.

**Comment by leeyeh** [comment]
Any idea or workaround?

**Comment by Victorystick** [comment]
How would you go about ignoring them? Why not just leave them as external dependencies, that just don't get loaded?

**Comment by leeyeh** [comment]
Sorry for lack of details.

```javascript
var memcpy = null; try { memcpy = require("memcpy"); } catch (e) {}
if (memcpy) // ...
```
will be rolled to
```javascript
var require$$0$2 = _interopDefault(require('memcpy')); // throw
// .....
memcpy = null; try { memcpy = require$$0$2; } catch (e) {}
```

**Comment by Victorystick** [comment]
Hmm... So it'd be enough for the CommonJS plugin to replace `require('memcpy')` with a throwing function call?

**Comment by leeyeh** [comment]
That'll do.

**Comment by leeyeh** [comment]
That will do.

**Comment by southpolesteve** [comment]
Just wanted to chime in and say I ran into this exact issue today. I am trying to use rollup to deploy bundled server JS to AWS Lambda. Rollup is ideal because it will allow us to upload only code that is actually needed by the function. Modules ( `ioredis` in my case ) that have optional dependencies will have the exact behavior described by @leeyeh

**Comment by leeyeh** [comment]
Has any solution been implemented? I didn't see anything related in change logs.

**Comment by TrySound** [comment]
@leeyeh It's related to commonjs plugin. You can open issue there.

**Comment by paulfalgout** [comment]
Actually I have the same problem but without the commonjs plugin.

We have an optional dependency on a library that if you're using the build in a `<script>` with UMD and the dependency is not in the global scope, the features that don't require that dependency should work..

But rollup creates the line:
`MyOptionalDependency = 'default' in MyOptionalDependency ? MyOptionalDependency['default'] : MyOptionalDependency;`

And this fails of course if MyOptionalDependency was never loaded.

**Comment by bfred-it** [comment]
Related: https://github.com/rollup/rollup/issues/1385

Is this still an issue?
