### ISSUE TITLE
[Feature Request] Add only option to external

### ISSUE THREAD

**Issue by NE-SmallTown** [rollup/rollup-plugin-node-resolve#245]
### Feature Use Case
At now, the `only` option passed into `node-resolve` plugin will **not** add corresponding external to the rollup config/options object, so, when we do build, there will be many warnings like "Treating [module] as external dependency"(https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency) which tell us to add modules below to the `external` option. Although that's not a problem but indeed is a little annoying so I think we should fix it.

### Feature Proposal

Add `only` option to the rollup external option

**Comment by lukastaegert** [comment]
From the docs:

> Set to an array of strings and/or regexps to lock the module search
to modules that match at least one entry. Modules not matching any
entry will be marked as external

With that in mind, this could actually be considered a bug. The IMO correct way to do this, though, would be to return `false` from the resolveId hook instead of patching the options: https://rollupjs.org/guide/en/#resolveid

This should prevent warnings emitted by Rollup as well.

**Comment by NE-SmallTown** [comment]
Thanks for your response. The doubt here is that if I add a extra option(like `resolveId` you said above), then IMO there is no need to add the `only` option, because when I add a `only` option, I want to tell node-resolve treat them as dependencies and **all others** as external, this should be a default behavior.

If we **have to** add extra option to archive this, I think maybe I can **just only** use the `external` option of rollup **rather than** use the `only` option of node-resolve. So, given this option has been provided by node-resolve, I think maybe we can "fix" it?

By the way, the case I encountered is when the `only` is '[/project-name\/src/i]`, seems something like `@babel/runtime-corejs3` will emit the warning, hope this info helps!

**Comment by lukastaegert** [comment]
I think you misunderstood my response, I am talking about how to implement it. resolveId is not an option but a plugin hook that is already used by this plugin to do its thing. Please check the link I added. This is meant for someone who wants to fix this.

**Comment by NE-SmallTown** [comment]
sorry, I didn't look up that carefully, now I get what you mean, thanks!

**Comment by shellscape** [comment]
@lukastaegert does this need to be transferred to `rollup/plugins`?

**Comment by shellscape** [comment]
Closing for now. Please re-create and reference this issue in https://github.com/rollup/plugins if it needs to be discussed more.
