### ISSUE TITLE
Couldn't find preset "es2015-rollup" relative to directory "[...]rollup-plugin-node-resolve/src"

### ISSUE THREAD

**Issue by bennybennet** [rollup/rollup-plugin-node-resolve#27]
I do not use the es2015-rollup preset in my project. As so i do get the error:
`Couldn't find preset "es2015-rollup" relative to directory "[...]rollup-plugin-node-resolve/src"`
when using the node-resolve plugin.

As a workaround I npm install the preset myself, but I do think that could be easily fixed when putting
`"babel-preset-es2015-rollup": "^1.0.0"` 
inside the dependencies instead of devDependencies.

**Comment by TrySound** [comment]
@bennybennet Show config and package.json

**Comment by bennybennet** [comment]
My config and package.json are irrelevant. Everything one must know is described above.
I do not use babel preset es2015-rollup and therefor rollup-plugin-node-resolve is missing it because it doesn't claim it as a runtime dependency.

**Comment by TrySound** [comment]
@bennybennet Hm.. nope. I can't answer you without any real information. I guess you do something wrong. It's not the problem of this plugin.

**Comment by eventualbuddha** [comment]
It's possible that the `.babelrc` is being distributed with the package when it shouldn't be. I'll look when I'm back at a computer.

**Comment by bennybennet** [comment]
The Problem is:
This plugin has it's own .babelrc (located in src/) and the babelrc requires the preset es2015-rollup. But this plugin does NOT declare the dependency in his own package.json.

**Comment by bennybennet** [comment]
@eventualbuddha any news on this issue?

**Comment by TrySound** [comment]
Now it doesn't have babel at all. So close
