### ISSUE TITLE
Documentation for default values for options

### ISSUE THREAD

**Issue by maranomynet** [rollup/rollup-plugin-node-resolve#29]
It would be a huge improvement if the README would list the default values of each option for the plugin.

It's kind of cumbersome to have to read the source to figure those out.

(Same applies to a lot of the other rollup plugins.)

**Comment by TrySound** [comment]
@maranomynet PR welcome.

**Comment by maranomynet** [comment]
A PR is sure to follow once I've poked at this some more.
