### ISSUE TITLE
Rollup generate bundles that require dependencies that are not needed.

### ISSUE THREAD

**Issue by rvlander** [rollup/rollup-plugin-node-resolve#33]
I am trying to use rollup with an existing node project (all dependencies are called using require)
One of the dependecy in nunjucks a well known templating engine.

Rollup seem to resolve a dependency of nunjucks: fsevents via chokidar, which is a OS dependent module not used under Linux.

Same problem with knex module which requires sqlite3 which is not used in this case.

Of course we can just ignore this modules in conf, but shouldn't it be smart enough to do it by itself?

[Edit] Even if you skip this modules, the generate bundle.js (launched with node) crash saying these modules are missing.

**Comment by TrySound** [comment]
@rvlander You shouldn't bundle dependencies of you node projects. Anyway it's not efficient because of commonjs.

**Comment by rvlander** [comment]
@TrySound what do you mean by you shouldn't bundle dependencies of your node project? I though that rollup's aim was to have a single js file containing all the code you need in production (plus binaries aside).

**Comment by TrySound** [comment]
@rvlander It's good for client. But bundling whole server side is a shoot at a leg. IMHO. Also moving binaries does not give you guarantee in success.

**Comment by rvlander** [comment]
@TrySound I understand your concerns. But the  is too shorten deployment phase of our back-end by reducing the code that is uploaded to our server. We now that our dev environment is the same as our production environment, hence, binaries are not a problem: they will work. Why do you think bundling all in a single file is a shoot in the leg?

**Comment by Victorystick** [comment]
@rvlander Using Rollup to bundle an app works well as long as you're working with ES modules. The CommonJS plugin can be used to include a few required dependencies _not written in ES modules_, but it isn't an ideal solution.

It may make more sense for you to bundle all ES modules first using Rollup, and using a tool like Webpack for the rest.
