### ISSUE TITLE
Node Resolve not finding Browser.js (or browser.min.js)

### ISSUE THREAD

**Issue by mgarf** [rollup/rollup-plugin-node-resolve#36]
I was trying to bundle React-Komposer into my react project but when I try to use CommonJS & Node Resolver to import it, I get thrown the following error:

`[Error: Module C:\Users\*******.******\Desktop\*******\JSApps\node_modules\react-komposer\index.js does not export compose (imported by C:\Users\*****.******\Desktop\*******\JSApps\containers\******UI.js)]`

The Rollup build looks like this: 

```
rollup.rollup({
    entry: appPath + '/'+folder+'/main.js',
    plugins: [
        nodeResolve({
            skip: ['react','react-dom'],
            jsnext: true,
            main: true,
            browser: true
        }),
        commonjs(),
        babel({
            "presets": ["react", "es2015-rollup"],
            comments: false
        }),
        uglify()
    ]
})
```

File Directory for the node module looks like this: 
- 0  react-komposer
- 1. index.js
- 2. dist
- 2.1 browser.js
- 2.2 browser.min.js
- 2.3 index.js
- 2.4 util.js
- 2.5 window_bind.js

The root index.js just contains this line of code: 

`module.exports = require('./dist/index');`

**Comment by bfred-it** [comment]
Closing for the age of the ticket. If you still need this, leave a comment.
