### ISSUE TITLE
Skipping `jsnext: true` for a single module?

### ISSUE THREAD

**Issue by girvo** [rollup/rollup-plugin-node-resolve#37]
I have a particular module that _does_ define the `jsnext` field, which is lovely, except it's using features that my ES2015 compiler can't handle at this point in time. I'd like to make that single module use the `main` property instead, but keep `jsnext` on for all the other modules: is this possible?

**Comment by bfred-it** [comment]
Closing for the age of the ticket. If you still need this, leave a comment.
