### ISSUE TITLE
Tree shaking not applied for node modules

### ISSUE THREAD

**Issue by blacksonic** [rollup/rollup-plugin-node-resolve#39]
When i use rollup with node_modules unused exports also appear in the bundled file.
Shouldnt it apply tree shaking also for node_modules? Or just im making something wrong.
Of course these unused exports disappear when uglified, but according to the official Rollup examples these should not be there before uglify.

I made an example repo to show my problem.
https://github.com/blacksonic/es2015-tree-shaking

I use RxJS, and it always applies operators for example, which makes the size bigger. Even if i uglify.

**Comment by Victorystick** [comment]
Closing in favor of rollup/rollup#663.
