### ISSUE TITLE
Is it possible to get THREE.js?

### ISSUE THREAD

**Issue by sasha240100** [rollup/rollup-plugin-node-resolve#42]
I just tried to do this but it shows
![image](https://cloud.githubusercontent.com/assets/7657429/15793211/30c1a85e-29eb-11e6-96a7-4d8b67e488e3.png)

And then all `THREE.Vector3` or smth like that are replaced with `undefined`

**Comment by TrySound** [comment]
@sasha240100 You should use entry point which is specified in main field. That file contains all in one.

**Comment by Rich-Harris** [comment]
You'll also need [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs), since Three doesn't currently distribute an ES module bundle. So your config will look something like this:

```js
// rollup.config.js
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: 'src/index.js',
  dest: 'dist/bundle.js',
  plugins: [
    nodeResolve({ main: true }),
    commonjs({ include: 'node_modules/**' })
  ]
};
```

**Comment by andrevenancio** [comment]
I know this is an old issue, but out of curiosity, with three currently on version 98, and you did a complete re-write of it around 2 years ago I think @Rich-Harris Why don't I have access to tree shaking?

```
import { Vector2 } from 'three';

const test = new Vector2();
```

Using latest version of rollup I effectively have everything from three being added to my bundle.js Shouldn't I just have the Vector2?
