### ISSUE TITLE
Please document usecases

### ISSUE THREAD

**Issue by MartinMuzatko** [rollup/rollup-plugin-node-resolve#47]
Hello there!
I'm trying to get rollup to work with node modules. The README doesn't give me any clue whether or not I need that so I can simply require/import npm modules.

I'd appreciate efforts to clarify why or why not I need this plugin. Thanks in advance.

**Comment by TrySound** [comment]
Hi, @MartinMuzatko! Readme has a link to resolver algorithm which describes process in details.
https://nodejs.org/api/modules.html#modules_all_together

**Comment by TrySound** [comment]
To clarify
```js
require('module');
// will look module in node_modules then in builtin modules (fs, path etc)
require('./module');
// will detect './' and look for local `module.js` in current directory
```
rollup works in the same way with local modules and ignores global. This plugin resolves global modules to let rollup process them as local.

**Comment by MartinMuzatko** [comment]
Thank you for clarification.
