### ISSUE TITLE
Module PATH does not export NAME (imported by PATH)

### ISSUE THREAD

**Issue by demrks** [rollup/rollup-plugin-node-resolve#52]
I'm trying to import an external NPM dependency with `rollup`. In my case — but I also tried it with other libraries — it's [lory.js](https://github.com/meandmax/lory), which also uses `jsnext:main` in the `package.json`:

```
npm install --save lory.js
```

```javascript
// main.js
import { lory } from 'lory.js';

const loryInstance = lory(document.querySelector('.js-carousel'));
```

My `rollup.config.js` looks very similar to what's described in the [rollup-plugin-babel documentation](https://github.com/rollup/rollup-plugin-babel):

```javascript
import babel from 'rollup-plugin-babel';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'main.js',
  dest: 'bundle.js',
  plugins: [
    nodeResolve(),
    babel({
      exclude: 'node_modules/**'
    })
  ]
};
```

Then, whenever I run `rollup --config rollup.config.js`, I get this error message:

```
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
Module PATH/node_modules/lory.js/dist/lory.js does not export lory (imported by PATH/main.js)
```

Is this a bug or the expected behaviour? 

_As a side note:_ I also tried to bundle it with browserify and it works, so it doesn't seem to be a problem with lory itself.

**Comment by TrySound** [comment]
@demrks `jsnext` should be enabled by an option. `module` alternative is enabled by default.
https://github.com/rollup/rollup-plugin-node-resolve#usage
Error causes because of umd
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(this, function() {
```
this is not allowed inside modules according spec. If you still need to have a bundle this this version you can use `context` option of rollup which was realeased in the last rollup version.

**Comment by demrks** [comment]
Thanks, I already saw the `jsnext` option, but that didn't work either for some libraries. This is what I already tried with rollup.

- Just `jsnext` option

```javascript
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'main.js',
  dest: 'bundle.js',
  plugins: [
    nodeResolve({
        jsnext: true
    })
  ]
};
```

==>
```
Error parsing PATH/node_modules/lory.js/src/lory.js: Unexpected token (214:19) in PATH/node_modules/lory.js/src/lory.js
```

- Since I thought this might be caused by ES6 in `src/lory.js`, I tried to run it through babel:
```javascript
import babel from 'rollup-plugin-babel';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'main.js',
  dest: 'bundle.js',
  plugins: [
    babel(),
    nodeResolve({
        jsnext: true
    })
  ]
};
```
==>
```
Error transforming PATH/node_modules/lory.js/src/lory.js with 'babel' plugin: Couldn't find preset "stage-0" relative to directory "PATH/node_modules/lory.js"
```
- Then, I just dropped the `jsnext` option and tried to do it with and without the common js plugin
```javascript
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'main.js',
  dest: 'bundle.js',
  plugins: [
    nodeResolve(),
    commonjs({
        include: 'node_modules/**'
    })
  ]
};
```
==>
```
Module PATH/node_modules/lory.js/dist/lory.js does not export lory (imported by PATH/main.js)
```

Is there anything in the documentation that I missed? The lory was just an example. It happens to some libraries too that use the UMD format, and all of them work with browserify.

Sorry for the confusion.
