### ISSUE TITLE
Prefers `browser` field over `jsnext:main`

### ISSUE THREAD

**Issue by danreeves** [rollup/rollup-plugin-node-resolve#55]
With the config

``` javascript
...
nodeResolve({
    jsnext: true,
    browser: true,
}),
...
```

rollup will prefer the `browser` field over the `jsnext:main` of a dependency. 

For example, trying to use D3 will result in it using the bundled `browser` version giving you import/export errors. ([D3 package.json](https://github.com/d3/d3/blob/master/package.json#L19))

Looking at the code, I'm assuming it will prefer `browser` over everything. 

Is this expected behaviour? Certainly could do with at least documenting as a gotcha.

Thanks

**Comment by TrySound** [comment]
@danreeves It's not prefered. There is different resolver with browser flag. Try just to disable it.

**Comment by danreeves** [comment]
Sure, I understand why it's happening but that's an implementation detail. I was assuming that (a plugin for) rollup might want to prefer `jsnext:main` if it's enabled. It also doesn't help if I need to use a `browser` field for one dependency but want to use `jsnext:main` for anything else that has it available. I might be missing some subtleties but the ideal resolution order imo would be:

1. `module` (if enabled)
2. `jsnext:main` (if enabled)
3. `browser` (if enabled)
4. `main`

Does that make sense?

**Comment by mbrevda** [comment]
It would indeed [seem](https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L19) that this plugin perfers a `browser` version, if enabled, over a `jsnext:main`/`module`. Shouldn't that logic be reversed?

**Comment by kylecordes** [comment]
Looking back at this item, and at the shiny new way Angular 4-rc.1 is published, for example:

https://github.com/angular/common-builds/blob/master/package.json

I think we need a way to ask for "0. es2015" added to the beginning of the list above.  I wish I could get a sense of whether these various new fields that are appearing in package.json files have any kind of standardized syntax or semantics. But just looking at what seems to be happening "out there", it appears that "es2015" is being used for the most ideal way to consume libraries from rollup: as ES2015 modules with ES2015 code in them.

**Comment by bfred-it** [comment]
With `{browser:true}`, preferring `browser` over `jsnext:main`/`module` is the right choice. This way you get the right features at the expensive of three shaking/whatever-es-modules-offer. 

If it preferred `jsnext:main`/`module` over `browser` it'd break some packages in the browser, which is much less desirable.

**Comment by bfred-it** [comment]
I'm going to add a solution: `browser` is actually a map, so you can use it to redirect the `jsnext:main` file to the "`browser` module" with something like this:

```patch
 {
   "main": "build/d3.node.js", 
-  "browser": "build/d3.js",
+  "browser": {
+    "build/d3.node.js": "build/d3.js",
+    "index": "index.browser"
+  },
   "module": "index",
   "jsnext:main": "index"
 }
```

I'd suggest sending a PR to D3
