### ISSUE TITLE
Turning off "main" Option Breaks Local Imports

### ISSUE THREAD

**Issue by arashikou** [rollup/rollup-plugin-node-resolve#56]
If I turn off the `main` option, thus excluding non-ES6 npm packages, then I can no longer include my own local JS files that are not part of an npm package at all. They fail with an error like

```
Package ./foobar (imported by C:\Users\tc\Documents\temp\main.js) does not have a module or jsnext:main field. You should either allow legacy modules with options.main, or skip it with options.skip
= ['./foobar'])
Error: Package ./foobar (imported by C:\Users\tc\Documents\temp\main.js) does not have a module or jsnext:main field. You should either allow legacy modules with options.main, or skip it with option
s.skip = ['./foobar'])
    at Error (native)
    at Object.packageFilter (C:\Users\tc\Documents\temp\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:69:22)
    at C:\Users\tc\Documents\temp\node_modules\resolve\lib\async.js:118:32
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

I am seeing this with rollup v0.34.13 and rollup-plugin-node-resolve v2.0.0

Here is a Gist that minimally reproduces the issue: https://gist.github.com/arashikou/447e145ed5d104060b56d2be87ed4b7e

**Comment by niksy** [comment]
Same here.

**Comment by mecurc** [comment]
Seems like it so outdated, but i tied reproduced it here https://github.com/mecurc/56-rollup-issue and all works with latest versions.

Issue can be closed :)
