### ISSUE TITLE
merge builtins into this

### ISSUE THREAD

**Issue by calvinmetcalf** [rollup/rollup-plugin-node-resolve#57]
merging rollup-plugin-node-builtins seems like it would be a useful addition

**Comment by mecurc** [comment]
For what? I tried it and importing works fine with the latest versions of rollup and rollup-plugin-node-resolve.

Can it be closed too? No discussions here since 2016.

**Comment by mecurc** [comment]
Repro can be found here: https://github.com/mecurc/57-rollup-issue
