### ISSUE TITLE
Error: 'render' is not exported by node_modules/react-dom/index.js

### ISSUE THREAD

**Issue by FezVrasta** [rollup/rollup-plugin-node-resolve#58]
When I use `nodeResolver` I get:

```
Error: 'render' is not exported by node_modules/react-dom/index.js
```

trying to run `import { render } from 'react-dom'`

What's up?

**Comment by Victorystick** [comment]
This is related to CommonJS's dynamic nature. Rollup doesn't find the export; see the [documentation](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports) for a workaround.
