### ISSUE TITLE
jsnext:browser?

### ISSUE THREAD

**Issue by wearhere** [rollup/rollup-plugin-node-resolve#60]
I have a package that targets Node and the browser but not isomorphically—I have a Node-specific script and a browser-specific script. I wish to bundle each of these in CJS and ES6 formats. How may I do this? Seems like `jsnext:browser` is required:

```
"main": "dist/node/index.js",
"jsnext:main": "dist/node/index.es2015.js",
"browser": "dist/browser/index.js",
"jsnext:browser": "dist/browser/index.es2015.js"
```

**Comment by nolanlawson** [comment]
@wearhere see https://github.com/rollup/rollup-plugin-node-resolve/issues/8#issuecomment-257323750

**Comment by joaovieira** [comment]
@nolanlawson how's that resolved by the different bundlers (inc. Browserify, Rollup, Webpack) if I just require the module name? I guess we have to reference the path explicitly?

**Use case for jsnext:browser**: 

I would like to have two versions of the my library for the browser as well, where the "next" version uses ES modules and does not polyfill the Fetch API, while the normal transpiles and polyfills. And I'd like users of those bundlers to be able to use the "next" version for the browser if they're not targeting older browsers.

**Comment by joaovieira** [comment]
Oh, does it resolve the `main`/`jsnext:main` path first and then try again which will hit the `browser`? Will give it a try 👍

**Comment by bfred-it** [comment]
@joaovieira you can do that as described by @nolanlawson

**Comment by joaovieira** [comment]
@bfred-it thanks, that guided me to it - browser paths are relative. I got it working with:

```javascript
"main": "dist/lib.polyfill.js",
"module": "dist/lib.es6.polyfill.js",
"browser": {
  "./dist/lib.es6.polyfill.js": "./dist/lib.es6.js"
}
```

@wearhere I guess for you would be:

```javascript
"main": "dist/node/index.js",
"module": "dist/node/index.es2015.js",
"browser": {
  "./dist/node/index.js": "./dist/browser/index.js",
  "./dist/node/index.es2015.js": "./dist/browser/index.es2015.js"
}
```
