### ISSUE TITLE
Should show source location with preferBuiltins

### ISSUE THREAD

**Issue by futurist** [rollup/rollup-plugin-node-resolve#61]
When source contains builtin modules, like `util`, below warning will show:

> preferring built-in module 'util' over local alternative at '/home/1111hui/public_html/node_modules/util/util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning

It shows the local module position, 
But don't show the exact source location, should it show?

**Comment by kopax** [comment]
Hi @futurist I have the same issue did you you solve it?

**Comment by futurist** [comment]
no, no one answer and I skipped this problem

**Comment by mecurc** [comment]
I tried with latest version of rollup and got output:
```bash
$ rollup -c

src/index.js → dist/bundle.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
util (imported by src/index.js)
(!) Unused external imports
promisify imported from external module 'util' but never used
created dist/bundle.js in 55ms
Done in 0.40s
```

Can be closed now :)
