### ISSUE TITLE
Problem with nested imports

### ISSUE THREAD

**Issue by Samlilli** [rollup/rollup-plugin-node-resolve#63]
I have the plugin working fine with initial imports of npm modules, however, when these modules have external dependencies, they are not resolved. I get the 'required is not defined' error in the devtools console. 

`import * as plumber from 'gulp-plumber';`

compiles to

```
var through2 = require('through2'); 
var EE = require('events').EventEmitter;
var gutil = require('gulp-util'); 
```

Any ideas on how I could fix this? (pretty sure it's not an issue with the plugin, just something I'm not quite getting). It could also be an issue with commonjs plugin for roll up, but I'm not sure.

**Comment by bfred-it** [comment]
Thanks. Any chance you can [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by mecurc** [comment]
It was fixed. Repro here: https://github.com/mecurc/63-rollup-issue

Issue can be closed now.

**Comment by mecurc** [comment]
Oh, sorry. Nested imports not working in case of:

es import 'package-X' and 'package-X' has some commonjs requires inside source code. But I don`t know it right behavior or not.

So, repository with repro:  https://github.com/mecurc/63-rollup-issue.

**Comment by mecurc** [comment]
This is not a rollup issue because gulp-plumber is node-only package and can be used only with node-side. Some of its dependencies node-specific.

Rollup and `rollup-plugin-node-resolve` works fine in this case. The issue can be closed.
