### ISSUE TITLE
Output requires module which isn't in the dependency chain

### ISSUE THREAD

**Issue by viveleroi** [rollup/rollup-plugin-node-resolve#65]
I have the [uuid module](https://www.npmjs.com/package/uuid) as a dependency, and I have `browser: true` in the nodeResolve plugin config.

The uuid module has a `uuid.js` main file, which has `require('./lib/rng')`.

However, there are two different lib files, one which gets loaded in the browser:

`"browser": {"./lib/rng.js": "./lib/rng-browser.js"}`

With rollup, my umd output somehow has `require('crypto'))` *and* the `rng-browser.js` code which breaks my script. Since I'm using requirejs and crypto wasn't a module, I get:

`require.min.js:1 Uncaught Error: Script error for "crypto"`

The only reference to `require('crypto')` in the source files is the original `./lib/rng.js` which was replaced, so I'm confused where the name `crypto` is coming from.

I do see `Treating 'crypto' as external dependency` during the build process, but uuid is the only module I use that references crypto - which I confirmed by building a file with *only* `import uuid from 'uuid';`

**Comment by bfred-it** [comment]
Thanks. Any chance you can [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by markis** [comment]
I ran into the same problem and came across this issue.  Here is a repro repository: https://github.com/markis/rollup-uuid-repro

**Comment by hueyhe** [comment]
Any update? According to [this issue](https://github.com/rollup/rollup-plugin-commonjs/issues/145#issuecomment-267033378), solution to this problem seems to be putting node resolve plugin before common js plugin. I tried but it didn't work. I think the repro that @markis  provided above illustrates my problem.

**Comment by hueyhe** [comment]
> I ran into the same problem and came across this issue. Here is a repro repository: https://github.com/markis/rollup-uuid-repro

@markis Try to place typescript plugin after common js plugin. After reading source code, I found that [this line](https://github.com/rollup/rollup-plugin-node-resolve/blob/f8dfa5770b1bfffd7c97ba2923d58a5d8ac4d4ac/src/index.js#L81) would ignore all `importee` that processed by other plugins. Make sure node resolve plugin runs first.

**Comment by mecurc** [comment]
Looks like this issue can be closed now :)
