### ISSUE TITLE
Error with wrong local import, leads to recursive loop

### ISSUE THREAD

**Issue by ArthurClemens** [rollup/rollup-plugin-node-resolve#66]
Update: seems to be related to rollup/rollup#1025. But the proposed solution does not solve the issue: it no longer loops, but (correct) updates are not propagated during watch.

---

My understanding was that rollup-plugin-node-resolve resolves files in `node_modules`. Nevertheless it raises an error if a local file import is incorrect. The error leads to a recursive loop, so the watch that I have running crashes. I then need to quit the process, and often kill the webserver process that is still running. So I would call this a crashing bug.

It happens when 
```
import {Page} from '../styles';
```
is written, instead of
```
import {Page} from './styles';
```

This is what is written to the console:
```
Could not resolve '../styles' from /Users/arthur/project/master/app/index.js
Error: Could not resolve '../styles' from /Users/arthur/project/master/app/index.js
    at Error (native)
    at /Users/arthur/project/master/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/arthur/project/master/node_modules/resolve/lib/async.js:55:18
    at load (/Users/arthur/project/master/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/arthur/project/master/node_modules/resolve/lib/async.js:92:31)
    at /Users/arthur/project/master/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
bundling...
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at deepClone (/Users/arthur/project/master/node_modules/rollup/src/utils/object.js:24:26)
    at deepClone (/Users/arthur/project/master/node_modules/rollup/src/utils/object.js:36:18)
     etc.
```

My config setting is
```
resolve({
    jsnext: true,
    main: true
})
```

**Comment by bfred-it** [comment]
Thanks. Any chance you can [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by ArthurClemens** [comment]
It has been fixes because I no longer have the issue.
