### ISSUE TITLE
npm-link

### ISSUE THREAD

**Issue by lsbardel** [rollup/rollup-plugin-node-resolve#67]
I have a library that bundles together several rollup-friendly libraries.
Everything works very well, but when I use `npm-link` on any of the libraries things don't work as expected anymore.

The resulting bundle includes imported libraries more than once.
Not a big deal, this is development issue, but the bundle can get quite big during development

**Comment by Reinmar** [comment]
We've experience the same issue.

I created a small test project in https://github.com/ckeditor/ckeditor5-design/tree/81a16f0b01a017538224c1eb38b253d390634242

It uses https://github.com/lerna/lerna to manage several packages – after running it (`lerna bootstrap`) all the deps are symlinked between each other.

I've tested Webpack and Rollup. Webpack (and Browserify) [works fine](https://github.com/ckeditor/ckeditor5-design/blob/81a16f0b01a017538224c1eb38b253d390634242/output-webpack.js#L78) – the `c2` console log is there only once. In Rollup's output it's [included twice](https://github.com/ckeditor/ckeditor5-design/blob/81a16f0b01a017538224c1eb38b253d390634242/output-rollup.js#L20).

This is a serious issue as e.g. `instanceof` checks fail, variables scoped in modules will be duplicated, etc.

**Comment by yaycmyk** [comment]
I'm seeing the same thing. @Rich-Harris in the issue where you merged symlink support, you mentioned it would only work for the "default resolver". Does that not include this plugin?

**Comment by muyi0327** [comment]
@Reinmar +1

**Comment by Reinmar** [comment]
We prepared a PR for this bug: https://github.com/rollup/rollup-plugin-node-resolve/pull/82 :) Works in our case ([CKEditor 5](https://github.com/ckeditor/ckeditor5)).

**Comment by lsbardel** [comment]
Is closed equivalent to resolved?

I still have the same issue when using three dependencies
A => B => C
A link B & C
B link C

some information would be great
