### ISSUE TITLE
Could not get `browser` field to work

### ISSUE THREAD

**Issue by unional** [rollup/rollup-plugin-node-resolve#74]
Tried to follow the README to use the browser field in `package.json` but can't get it to work.

The browser field should be correct as I can get `webpack` to bundle the project correctly.

```js
// package.json
{
  "browser": {
    "./dist/es5/environments.js": "./dist/es5/environments-browser.js"
  },
}

// rollup.config.es2015.js

...
  plugins: [
    ...
    nodeResolve({
      browser: true
    })
  ]
```
There is the repo: https://github.com/unional/aurelia-logging-color

You can see that the bundled file is bundled with `environments.js` instead of `enviornments-browser.js`:
https://github.com/unional/aurelia-logging-color/blob/rollup-browsers-spec/dist/aurelia-logging-color.es2015.js#L238
https://github.com/unional/aurelia-logging-color/blob/rollup-browsers-spec/src/environments.ts#L5

**Comment by bfred-it** [comment]
Is this still an issue? I see a rollup.config in your repo

**Comment by unional** [comment]
Unfortunately likely not. Due to this issue, I am currently not using the browser-spec.
I have updated the OP to point to a branch that show this issue.

**Comment by mecurc** [comment]
2 years since it was opened and no one writes updates here. Can it issue be closed?
