### ISSUE TITLE
'events' is imported by lib/Main.js, but could not be resolved – treating it as an external dependency

### ISSUE THREAD

**Issue by johnstew** [rollup/rollup-plugin-node-resolve#76]
I'm currently using nodes event emitter for some client side code. Here is my rollup config.

```js
import { join } from 'path';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: join(__dirname, '/lib/index.js'),
  format: 'es',
  plugins: [
    babel(),
    nodeResolve({
      extensions: ['.js'],
      main: true,
      browser: true,
      preferBuiltins: true
    }),
    commonjs({
      sourceMap: false,
    })
  ],
  dest: 'index.rollup.js'
};
```

I thought the preferBuiltIns option fixed this issue but I'm getting this.
```
'events' is imported by lib/Main.js, but could not be resolved – treating it as an external dependency
```

Seems like with preferBuiltins option enabled I shouldn't need to use [namedExports](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports).

**Comment by cwilling** [comment]
I had exact same issue which now seems resolved by adding [rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins) plugin

**Comment by mecurc** [comment]
Seems it resolved. Can we close the issue?

**Comment by cwilling** [comment]
It's resolved for me (as above) but can't speak for OP

**Comment by mecurc** [comment]
Then, I think it can be closed for now.

How many people using nodejs event emitter on client side? :)

Can be closed now. reopen if necessary/ :)

**Comment by johnstew** [comment]
💯
