### ISSUE TITLE
Option to treat node_modules as external

### ISSUE THREAD

**Issue by battmanz** [rollup/rollup-plugin-node-resolve#77]
The *only* reason I am using the `rollup-plugin-node-resolve` is so that I get the syntactic advantage of being able to import from the `index.js` file.

For example:
```javascript
import from './foo';
```
instead of

```javascript
import from './foo/index';
```

I still want everything inside of the `node_modules` folder to be considered `external`, which as I understand it, is the default behavior (without the plugin).
* Does it make sense for this plugin to have an option to get the behavior I want?
* Does it make more sense to create a new plugin?
* Or should I just do what I'm currently doing which is this

```javascript
export default {
  entry: 'src/foo.js',
  plugins: [
    nodeResolve()
  ],
  external(id) {
    return id.indexOf('node_modules') >= 0;
  }
}
```

**Comment by jknight12882** [comment]
👍 on this for me as well

**Comment by thisconnect** [comment]
Shouldn't this be possible with the `skip` option?

**Comment by r24y** [comment]
If there is a `skip` option, then it seems like this would be a documentation issue, not a code issue. The README for this repo doesn't seem to say anything about `skip`.

**Comment by maxkueng** [comment]
I do this:

```js
const pkg = JSON.parse(fs.readFileSync(path.resolve('./package.json'), 'utf-8'));
const external = Object.keys(pkg.dependencies || {});

export default {
  entry: 'src/foo.js',
  plugins: [
    nodeResolve(),
  ],
  external,
};
```

I'm not a Rollup expert but this solution seems to work so far.

**Comment by thisconnect** [comment]
@r24y oups seems like skip has been removed in 3.0.0 https://github.com/rollup/rollup-plugin-node-resolve/blob/master/CHANGELOG.md

**Comment by battmanz** [comment]
@maxkueng In most cases, I think your solution and my solution will end up with the same results. However, we are approaching it from different angles. You are saying "anything in `package.json` is an external module". Whereas I'm saying "anything in `node_modules` is an external module".  There are cases where we might end up with different results.

**Example:**
It's very common when building an Angular 2 library (not an app -- a library) to list `@angular/core`, `@angular/http`, `rxjs`, etc as `peerDependencies`. Sure, we can modify your code to include `peerDependencies`:

```ts
const external = Object.keys(pkg.dependencies || {}).concat(Object.keys(pkg.peerDependencies || {}))
```

... but what if a developer forgets to add a package to the `peerDependencies` -- an easy mistake to make? Using your code, the package will be included in the rollup bundle -- thus making it larger than intended. Using my code, the package will still be external.

**Question**
Which approach is better / less-error prone? I don't know. Are there any rollup experts that could shed some light on this subject?

**Comment by PeteJodo** [comment]
one issue with 
```js
  external(id) {
    return id.indexOf('node_modules') >= 0;
  }
```
is that what's passed to `require` after the build looks like `../node_modules/my-dependency` which for me isn't useful because the package isn't the top level, itself will be a dependency

**Comment by awerlang** [comment]
The workaround

```
external(id) {
  return id.indexOf('node_modules') >= 0;
}
```

doesn't work if you import built-ins like `http`.

This works (ignores everything containing `.`, `/`, `\`):

```
external(id) {
  return /^[^./\\]+$/.test(id);
},
```

Another option is using the `moduleDirectory` option (but shows warnings):

```
resolve({
  customResolveOptions: {
    moduleDirectory: 'fake_modules',
  },
}),
```

Also, there's the [rollup-plugin-local-resolve](https://www.npmjs.com/package/rollup-plugin-local-resolve) plugin that just implements the `./index.js` lookup.

**Comment by DuBistKomisch** [comment]
None of the solutions here quite worked for me unfortunately. Misbehaving npm dependencies (e.g. `socket.io-client`) can still break out into the bundle in weird ways.

For the record webpack has a [simple solution](https://www.npmjs.com/package/webpack-node-externals) which worked perfectly.

**Comment by cameron-martin** [comment]
Using the following configuration seems to work well:

```
        resolve({
            only: [/^\.{0,2}\//],
        }),
```

This makes anything that doesn't start with `/`, `./` or `../` as external, which is exactly the things which *aren't* loaded from `node_modules` as per the [node resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together).

**Comment by TrySound** [comment]
Here's universal function I use everywhere.
```js
const external = id => !id.startsWith('\0') && !id.startsWith('.') && !id.startsWith('/');
```
Here's rollup thread about this option
https://github.com/rollup/rollup/issues/1343

**Comment by mirismaili** [comment]
Thank [@maxkueng][1] for [his post][2]. I improved it by adding node built-in modules (like `fs` and `path`). Use:

```javascript
import builtins from 'builtin-modules/static'
const pkg = require('./package.json')
// ...
export default {
	external: builtins.concat(Object.keys(pkg.dependencies || {})),
    // ...
}
```
***
See [builtin-modules](https://www.npmjs.com/package/builtin-modules) on *npmjs.com* and also see: 

https://github.com/rollup/rollup-plugin-node-resolve#resolving-built-ins-like-fs


  [1]: https://github.com/maxkueng
  [2]: https://github.com/rollup/rollup-plugin-node-resolve/issues/77#issuecomment-297992040

**Comment by maxkueng** [comment]
@mirismaili Wow, it's been a while. Nowadays I just use [rollup-plugin-auto-external](https://www.npmjs.com/package/rollup-plugin-auto-external) like this:

```js
import autoExternal from 'rollup-plugin-auto-external';

export default {
  plugins: [
    autoExternal(),
    ...
};
```

**Comment by mirismaili** [comment]
@maxkueng Wow! Why anyone hadn't said this! Thanks anyway.
