### ISSUE TITLE
Remove jsnext:main support in next major release

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup-plugin-node-resolve#78]
ref https://github.com/infernojs/inferno/pull/830

**Comment by kylecordes** [comment]
I don't know enough about this to know if it is a good idea; but it would be quite easy to do downstream of my PR:  https://github.com/rollup/rollup-plugin-node-resolve/pull/85

**Comment by mecurc** [comment]
Already deprecated with the latest version. Can we close the issue?
