### ISSUE TITLE
Global imports are included multiple times

### ISSUE THREAD

**Issue by ryx** [rollup/rollup-plugin-node-resolve#80]
Hi. I am using rollup-plugin-node-resolve for bundling a base library together with a set of plugins (linked in as sub-modules) and a small bootstrapping code.

The sub-modules all import the base library (a global module), which is also included separately in the bundle. My assumption was that the module resolution would include the global module only once. But instead the global module is embedded for each import statement in the plugins, so there is a huge duplication of code inside the generated output.

Here is an example:
```javascript
// module 'base-library'
class Base {
  initialize(config) {}
  sayHello() {
    console.log('Hello');
  }
}
const base = new Base();
export default base;

// module 'plugin-test1'
import base from 'base-library';
class Test1 {
  constructor(foo) {
    base.sayHello();
  }
}

// module 'plugin-test2'
import base from 'base-library';
class Test2 {
  constructor(foo) {
    base.sayHello();
  }
}

// glue code
import base from 'base-library';
import Test1 from 'plugin-test1';
import Test2 from 'plugin-test2';

base.initialize();
new Test1();
new Test2();
```

The resulting code will include the module 'base-library' three times, instead of only once. Is there any chance to get a behavior where the global library will be embedded only once?

Thanks in advance.

**Comment by yyc-git** [comment]
How to solve it? I have meet the problem too!

**Comment by yyc-git** [comment]
Hello again! I have find a way to solve it:
skip 'base-library' in rollup-plugin-node-resolve;
use rollup-plugin-includepaths for it;

so the rollup.config.js may like:

import nodeResolve from "rollup-plugin-node-resolve";
import includePaths from "rollup-plugin-includepaths";

export default {
    entry: "xxx",
    indent: "\t",
    plugins: [
        nodeResolve({
            skip: [
                "base-library"
            ]
        }),
        includePaths({
            paths: ["the_dirPath-library"],
            extensions: [".js"]
        })
    ],
    ...
}

**Comment by yyc-git** [comment]
It's still has problems.
if work together with rollup-plugin-typescript plugin, then the 'base-library' code will still be imported  multiple times!

so maybe we must ensure that the 'plugin-test1','plugin-test2' npm package shouldn't has the 'base-library' in "dependencies" field in package.json!
that means remove the 'base-library' from "node_modules" dir in 'plugin-test1' and 'plugin-test2' npm package!

**Comment by ngryman** [comment]
@yyc-git Thanks for your workaround.

Still this is a major issue that many of us are facing. Three shaking is a cool feature but if it's not coupled with basic deduping, well it's only marketing then 😛

With nowadays `npm`/`yarn` deduping dependencies by default I guess it should be doable in a reasonable amount of time?

**Comment by mtrias** [comment]
Hello! 

Did anyone find a good solution for this?

I'm having the same issue in my setup (*). So, I wonder how people are distributing projects so that others can import both their projects and their dependencies at the same time without getting those dependencies duplicated in the final bundle.

(*)
- Project 1 exports A, and imports B
- Project 2 imports A, and imports B
so B gets duplicated when bundling project 2

**Comment by mtrias** [comment]
Update: using this plugin apparently addressed my use case https://github.com/tehvgg/rollup-plugin-force-binding. Testing now.

**Comment by caseyWebb** [comment]
The above plugin does not work for me.

I have KnockoutJS loaded via a CDN and in `globals`, and am importing knockout-punches from node_modules. However, since punches is importing it's own version of Knockout. I've tried just about everything I can think to try.

halp.

**Comment by caseyWebb** [comment]
FWIW, this can be solved from the publisher's side by ensuring that the shared lib (jquery, knockout, etc.) is listed under `peerDependencies`, and not `dependencies`. It's not very well documented, though, and takes quite a bit of struggling to find.

**Comment by sormy** [comment]
Trick with `peerDependencies` doesn't work if peer package somehow installed into child `node_modules` (for example, if it is installed as devDependency to run tests against specific version). 

Metro bundler has an option to remap and blacklist modules using `metro.config.js` with `resolver.blacklistRE` and `resolver.extraNodeModules`. Webpack has similar using `resolve.alias`. Rollup has nothing integrated and `rollup-plugin-node-resolve` just doesn't provide this option too.

Sad :-(

**Comment by mecurc** [comment]
I checked it with the latest versions. Works perfectly :) Module bundled only once.

Repro here: https://github.com/rollup/rollup-plugin-node-resolve/issues/80

Can be closed now.
