### ISSUE TITLE
package with sub-modules (ES6)

### ISSUE THREAD

**Issue by tiagoantao** [rollup/rollup-plugin-node-resolve#81]
I know that according to the node resolution algorithm a single file should be returned, but ES6 modules lend themselves to splitting content into sub-modules, say like this (lets call it package my_package):

`
- package.json
- lib
  - my_package
    - file1.js
    - file2.js
    - sub_package1
      - file3.js
      - file4.js`

Currently, as resolving requires a single file as entry point, such a file probably does a lot of `export from`s in order to make available all the content of the sub-modules.

Could there be anyway where we could do something file `import * from 'my_package/sub_package1/file3'`?

This would allow for a more declarative way of dealing with sub-modules and no need for a main/module entry that actually does a lot of `export from`

**Comment by bfred-it** [comment]
You can do exactly that, for example:

```js
import * from `rollup/dist/rollup.es.js`
```
