### ISSUE TITLE
Seems to fail to `require('./index')`

### ISSUE THREAD

**Issue by alexbepple** [rollup/rollup-plugin-node-resolve#87]
With this example: https://github.com/alexbepple/rollup-issue-require-index
I get the following error at runtime:

    Uncaught TypeError: l.setup is not a function
      at setupLock (actions.js:47)
      at Auth0Lock.Base (core.js:77)
      at new Auth0Lock (index.js:49)
      at makeAuth0Driver (makeAuth0Driver.js:149)
      at index.js:3
      at index.js:3

I can trace this to `node_modules/auth0-lock/lib/core/actions.js:32`. It seems that `require('./index')` is not resolved properly. I verified that the file is there.

<img width="434" alt="screenshot" src="https://cloud.githubusercontent.com/assets/159355/23811190/33d29406-05d5-11e7-92bf-dc7f75ec6b8f.png">

Any ideas?

**Comment by mecurc** [comment]
I tried to reproduce this with repro repository. Got errors not described here. Then I tried with updated versions. ( > 2 major versions in external packages). And Buble fails on package.json (оО). 

I think we should close this. If issue reproduces with latest packages (not from 2017) reopen it later.
