### ISSUE TITLE
Dependencies at a local path are not resolved.

### ISSUE THREAD

**Issue by kennethjiang** [rollup/rollup-plugin-node-resolve#88]
I have an npm dependency specified at local path (it is a path to a git submodule):

```
...
  "dependencies": {
    "3tk": "file:lib/3tk",
    ...
  },
...
```

`rollup -c` would fail with the this error:
```
Could not resolve '3tk' from /Users/kenneth/Projects/OctoPrint-Slicer/src/STLViewPort.js
```

However when I published `3tk` to npm and change `package.json` to be:
```
...
  "dependencies": {
    "3tk": "^0.1.0",
    ...
  },
...
```
everything worked.

Is it a user error, or is it because `rollup-plugin-node-resolve` doesn't correctly resolve npm package from local path?

**Comment by bhousel** [comment]
@kennethjiang You can probably use [rollup-plugin-includepaths](https://www.npmjs.com/package/rollup-plugin-includepaths).

**Comment by mecurc** [comment]
> @kennethjiang You can probably use [rollup-plugin-includepaths](https://www.npmjs.com/package/rollup-plugin-includepaths).

I think it can be closed :)
