### ISSUE TITLE
nodeResolve: Incremental lookup

### ISSUE THREAD

**Issue by mani0608** [rollup/rollup-plugin-node-resolve#89]
I am using ng2-select component in my application
https://github.com/valor-software/ng2-select. And i use rollup with following configuration

`gulp.task('rollup:app', function(){ return rollup.rollup( { entry: 'dist/app/main.prod.js', plugins: [ nodeResolve({ jsnext: true, main: true, module: true }), commonjs({ include: ['node_modules/rxjs/**', 'node_modules/ng2-select/**'], namedExports: { 'node_modules/ng2-select/bundles/ng2-select.umd.js':['SelectModule'] } }) ] }) .then(function(bundle) { bundle.write( { format: "iife", dest: "dist/app.bundle.js", sourceMap: true }); }); });`

Package.json of ng2-select includes both module and main. But the export is included in js file referred by main and not by module. The build process refers only file referred in module (index.js) and the build process fails with following error message,

`Error: 'SelectModule' is not exported by node_modules\ng2-select\index.js`

Is there any way i can make it refer, incrementally, the main file which is bundles/ng2-select.umd.js when the export is not found under module.

**Comment by bfred-it** [comment]
What do you mean by incremental?. Any chance you can [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by mecurc** [comment]
No updates since 2017. I think it can be closed now. Reopen if needed.
