### ISSUE TITLE
2.1.0 treating ES6 modules as external dependencies

### ISSUE THREAD

**Issue by msroberts** [rollup/rollup-plugin-node-resolve#93]
After updating to 2.1.0, rollup is not recognizing imported ES6 modules such as d3 or topojson.  I tested this by following the process here: [https://bl.ocks.org/mbostock/bb09af4c39c79cffcde4](https://bl.ocks.org/mbostock/bb09af4c39c79cffcde4).  With rollup-plugin-node-resolve set at version 2.0.0, it works as expected; however, with 2.1.0, it gives the message "Treating 'd3-selection' as external dependency" and does not include.  d3-selection's package.json has a module field.

**Comment by Rich-Harris** [comment]
Oh, that's odd — let me look into it. In the meantime, could you try adding `module: true` to the config, like so? Thanks

```js
import node from "rollup-plugin-node-resolve";

export default {
  entry: "index.js",
  format: "umd",
  moduleName: "d3",
  plugins: [node({ module: true })],
  dest: "d3.js"
};
```

**Comment by msroberts** [comment]
Still give the same error and does not include.  Also tried with jsnext but no difference.

**Comment by Rich-Harris** [comment]
I can't reproduce this — can you point me to a repo where this is failing please? [Here's the gist](https://gist.github.com/Rich-Harris/6b701db6d27eb783423ebd8098dec359) where I tried to reproduce it — it finds d3-selection without any problems, with or without `module: true`.

**Comment by msroberts** [comment]
I still get the error with the gist (but changed rollup version to 0.41 as npm could not find 0.46).

**Comment by Rich-Harris** [comment]
Oops, typo — meant 0.41.6. Can you detail the *exact* steps you took to get that error? If I clone that repo, install dependencies, and run Rollup, it works as expected:

```bash
git clone https://gist.github.com/6b701db6d27eb783423ebd8098dec359.git
cd 6b701db6d27eb783423ebd8098dec359
npm i
npm run build
open index.html
```

**Comment by filipesilva** [comment]
I'm getting this on Windows only. A repro can be found at https://github.com/filipesilva/node-resolve-windows-bug.

```
npm install
npm run rollup
```

On Windows the following message appears:
```
⚠️   'default' is imported from external module 'rollup' but never used

⚠️   '@angular/platform-browser-dynamic' is imported by src\main.js, but could not be resolved – treating it as an external dependency
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

⚠️   No name was provided for external module '@angular/platform-browser-dynamic' in options.globals – guessing '_angular_platformBrowserDynamic'
```

On Unix a bunch of `The 'this' keyword is equivalent to 'undefined'` appear instead, and the build is correctly generated.

**Comment by msroberts** [comment]
I'm on Windows too.  I get the same error in Command Prompt and Git Bash.

**Comment by Rich-Harris** [comment]
Oohhh... I wonder if this was caused by https://github.com/rollup/rollup-plugin-node-resolve/pull/53

**Comment by Rich-Harris** [comment]
This should be fixed in 2.1.1. Thanks

**Comment by msroberts** [comment]
Works now.  Thanks!

**Comment by bhousel** [comment]
For anyone who got here through googling and still has this issue, see https://github.com/rollup/rollup-plugin-node-resolve/issues/105#issuecomment-332640015
