### ISSUE TITLE
v2.1.0 and higher breaks babel:ing symlinked packages

### ISSUE THREAD

**Issue by lohfu** [rollup/rollup-plugin-node-resolve#98]
When upgrading from v2.0.0 to v2.1.0 or higher, it breaks my rollup-plugin-babel setup for local, symlinked packages.

While developing packages, I often symlink local copies into my `node_modules` folder, either manually or using `npm link`. Furthermore, I have gotten into the habit of not transforming my packages when publishing, but doing it in the local project.

```js
babel({
  include: [
    'node_modules/preact/**',
    'node_modules/preact-redux/**',
    'node_modules/comkit-preact/**',
    'client/**',
  ],
  babelrc: false,
  presets: ['es2015-rollup', 'es2016', 'es2017', 'stage-0'],
  plugins: [
    ['transform-react-jsx', { pragma: 'h' }],
  ],
})
```

`comkit-preact` is symlinked, and after the update the babel plugin will not transform the files in symlinked packages generating errors such as this:

```
Unexpected token
{ code: 'PARSE_ERROR',
  pos: 2588,
  loc: 
   { file: '/home/lohfu/lib/node/comkit-preact/src/CheckBoxGroup.jsx',
     line: 100,
     column: 6 },
  frame: ' 98: \n 99:     return (\n100:       <div class={classes}>\n           ^\n101:         {children}\n102:         <label class="icon" />' }
```

I understand this an unusual setup, but is there anyway to solve this easily?

**Comment by bfred-it** [comment]
Are you sure this isn't a `babel` or `rollup-plugin-babel` issue?

**Comment by lohfu** [comment]
@bfred-it sorry for the extremely slow response... i solved my issue by adding the 

```js
{
  customResolveOptions: {
    moduleDirectory: 'js_modules'
  }
}
```

essentially before version 2.1 the symlinked package still looked in the original package's `node_modules` folder, but since 2.1 i assume packages are only resolved relative to requiring file's actual location in the file system.

since "native" node also only looks relative to the current file's actual location, this is a reasonable change. in node i use the `app-module-path` module to add the main packages `node_modules` to the resolve paths so symlinked packages work as if they were normally installed there as well.

**Comment by mecurc** [comment]
Is it resolved?

No updates since 2017, can it be closed now?
